# Generated by Django 5.0.6 on 2024-06-27 09:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=1500)),
                ('upload_date', models.DateTimeField()),
                ('product_type', models.CharField(max_length=20)),
                ('product_brand', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PriceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product Prices Model')),
                ('default_price', models.FloatField()),
                ('discount_rate', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='product Images Model')),
                ('black_color', models.ImageField(upload_to='product_image_black')),
                ('white_color', models.ImageField(upload_to='product_image_white')),
                ('other_color_one', models.ImageField(upload_to='product_image_other_one')),
                ('other_color_two', models.ImageField(upload_to='product_image_other_two')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product Comments Model')),
                ('user_name', models.CharField()),
                ('comment_total', models.IntegerField()),
                ('content', models.CharField()),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='RatingStarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product Rating Stars Model')),
                ('total_stars', models.FloatField()),
                ('user_rate', models.IntegerField()),
                ('average_star', models.FloatField()),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products')),
            ],
        ),
    ]
