# Generated by Django 5.0.6 on 2024-06-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pricemodel',
            name='title',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ratingstarmodel',
            name='title',
            field=models.CharField(),
        ),
    ]
