# Generated by Django 5.0.6 on 2024-06-29 02:56
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_commentmodel_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='comment_model',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image_model',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price_model',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rating_model',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='pricemodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
        migrations.AlterField(
            model_name='ratingstarmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.products'),
        ),
    ]
