# Generated by Django 5.0.6 on 2024-06-25 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
