# Generated by Django 5.0.6 on 2024-06-26 06:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('banner', models.ImageField(upload_to='top_brand_banner')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
